### ISSUE TITLE
Can't run jekyll serve dockerfile on my machine

### ISSUE THREAD

**Issue by NealHumphrey** [codefordc/project-management#23]
Steps I took:
- run Docker Quickstart from docker toolbox on Windows 10
- ran `docker pull codefordc2/jekyll-serve:release`. This downloaded the image successfully ("Status: Downloaded newer image..."
- changed into housing-insights folder
- ran `docker run --volume $(pwd)/docs:/srv/jekyll -p 127.0.0.1:4000:4000 codefordc2/jekyll-serve`. Got error "Unable to find image 'codefordc2/jekyll-serve:latest' locall" error. 
- ran `docker run --volume $(pwd)/docs:/srv/jekyll -p 127.0.0.1:4000:4000 codefordc2/jekyll-serve:release` (to match the pull command explicitly). Got error:

```
time="2017-03-23T13:09:18-04:00" level=info msg="Unable to use system certificate pool: crypto/x509: system root pool is not available on Windows"
bundler: failed to load command: jekyll (/usr/local/bundle/bin/jekyll)
Bundler::GemNotFound: Could not find addressable-2.4.0 in any of the sources
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/spec_set.rb:87:in `block in materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/spec_set.rb:80:in `map!'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/spec_set.rb:80:in `materialize'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/definition.rb:176:in `specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/definition.rb:235:in `specs_for'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/definition.rb:224:in `requested_specs'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:118:in `block in definition_method'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/runtime.rb:19:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler.rb:100:in `setup'
  /usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.14.3/lib/bundler/setup.rb:20:in `<top (required)>'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

**Comment by NealHumphrey** [comment]
- Make sure that the Gemfile has `source 'https://rubygems.org'` at the top. 
- Clarify 2.i that the Dockerfile should be copied into the repository's root directory
- Clarify 2.ii that the custom name you use is what the image is called locally. If you are going to publish the image (i.e. to team members), you should be sure to namespace it to the codefordc2 org, eg. `docker build . -t codefordc2/{your-project}-jekyll`
- Make building a new jekyll dockerfile the default behavior, to make sure that any version and dependency issues are properly handled. Change the 'run' instructions (part 1) to assume that you are using an existing dockerfile (i.e. a project specific one). Only use the default codefordc build if the site was created using the auto-generate site tool from the top section (that way we know they should match). 
- Either here or up a level (i.e. in the project-management root) describe how to publish images.

**Comment by NealHumphrey** [comment]
- In the run instructions, add instructions to tell user to run `docker-machine ip` and substitute that IP address for the 127.0.0.1 ip
