### ISSUE TITLE
Can't run housing-insights docker-compose up

### ISSUE THREAD

**Issue by hansak11** [codefordc/project-management#28]
On Windows 10. Using virtualbox driver (had to these instructions to replace the docker-machine [instructions](https://github.com/docker/toolbox/issues/317))

We get this stack dump:

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 116, in perform_command
  File "compose\cli\main.py", line 876, in up
  File "compose\project.py", line 385, in up
  File "compose\project.py", line 590, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 73, in info
  File "site-packages\docker\utils\decorators.py", line 47, in inner
  File "site-packages\docker\api\client.py", line 183, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose
```

**Comment by mkalish** [comment]
If you weren't able to resolve the issue that you linked to, the docker-compose command will fail.  I would try running `docker-machine rm default` and restarting the docker quickstart terminal.

Also, what version of windows are you running?

**Comment by NealHumphrey** [comment]
We were able to resolve the issue in the link by following the instructions there (replacing the docker-machine) - I just linked to that for context. 

In later investigation, it appeared that the error was due to not having administrative priviledges on @hansak11 's machine. I tried to run a `docker pull codefordc2\housing-insights-jekyll` and it gave us an error message saying the code had to be run in elevated state. It's her work machine so we probably can't get admin rights, but she did some Googling and it looked like we might still get her running by building the images from a downloaded tarball and then composing with the local images available.

**Comment by mkalish** [comment]
I'm going to go ahead and closet this issue then.

**Comment by NealHumphrey** [comment]
@mkalish to be clear, this stack dump never got resolved. Only the one in the link, which replaced the driver w/ VirtualBox. But, as I said this issue looks like it's because of admin priviledges. OK closing just wanted to clarify it wasn't actually resolved.
